<?php

namespace ContainerSH1gWBy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAbonarServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Services\AbonarService' shared autowired service.
     *
     * @return \App\Services\AbonarService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/AbonarService.php';

        return $container->privates['App\\Services\\AbonarService'] = new \App\Services\AbonarService();
    }
}
