<?php

namespace ContainerWsfpgxS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransplantarServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Services\TransplantarService' shared autowired service.
     *
     * @return \App\Services\TransplantarService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/TransplantarService.php';

        return $container->privates['App\\Services\\TransplantarService'] = new \App\Services\TransplantarService();
    }
}
