<?php

namespace ContainerRu3cu7k;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAbonarBonsaiControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\Bonsai\AbonarBonsaiController' shared autowired service.
     *
     * @return \App\Controller\Bonsai\AbonarBonsaiController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/Bonsai/AbonarBonsaiController.php';
        include_once \dirname(__DIR__, 4).'/src/Services/AbonarService.php';

        return $container->services['App\\Controller\\Bonsai\\AbonarBonsaiController'] = new \App\Controller\Bonsai\AbonarBonsaiController(($container->privates['App\\Services\\AbonarService'] ?? ($container->privates['App\\Services\\AbonarService'] = new \App\Services\AbonarService())));
    }
}
