<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWsfpgxS\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWsfpgxS/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerWsfpgxS.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerWsfpgxS\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerWsfpgxS\App_KernelTestDebugContainer([
    'container.build_hash' => 'WsfpgxS',
    'container.build_id' => '6a43f859',
    'container.build_time' => 1623031225,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWsfpgxS');
