<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSH1gWBy\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSH1gWBy/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerSH1gWBy.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerSH1gWBy\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerSH1gWBy\App_KernelTestDebugContainer([
    'container.build_hash' => 'SH1gWBy',
    'container.build_id' => 'a740fbb5',
    'container.build_time' => 1622933562,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSH1gWBy');
