<?php

declare(strict_types=1);


namespace App\Tests\Services\Bonsai;

use App\Services\AbonarService;
use PHPUnit\Framework\TestCase;

class AbonarServicesTest extends TestCase
{
    private AbonarService $service;
    private \DateTime $ultimoAbono;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->service = new AbonarService();
        $this->ultimoAbono = new \DateTime('2020/03/21 12:00:00');
    }

    public function testAbonarBonsaiRetornaBoleano()
    {
        $result = $this->service->abonarBonsai($this->ultimoAbono);

        self::assertIsBool($result);
    }

    /** @Test*/
    public function testAbonarBonsaiPrimavera()
    {
        $estacion = new \DateTime('2020/04/24 12:00:00');
        $this->service = new AbonarService($estacion);

        $result = $this->service->abonarBonsai($this->ultimoAbono);

        $this->assertEquals(true, $result);
    }

    /** @Test*/
    public function testAbonarBonsaiPrimaveraMenosDe30Dias()
    {
        $estacion = new \DateTime('2020/03/24 12:00:00');
        $this->service = new AbonarService($estacion);

        $result = $this->service->abonarBonsai($this->ultimoAbono);

        $this->assertEquals(false, $result);
    }

    /** @Test*/
    public function testAbonarBonsaiOtono()
    {
        $estacion = new \DateTime('2020/10/21 12:00:00');
        $this->service = new AbonarService($estacion);

        $result = $this->service->abonarBonsai($this->ultimoAbono);

        $this->assertEquals(true, $result);
    }
    
    /** @Test*/
    public function testAbonarBonsaiVerano()
    {
        $estacion = new \DateTime('2020/08/21 12:00:00');
        $this->service = new AbonarService($estacion);

        $result = $this->service->abonarBonsai($this->ultimoAbono);

        $this->assertEquals(false, $result);
    }

    /** @Test*/
    public function testAbonarBonsaiInvierno()
    {
        $estacion = new \DateTime('2020/01/21 12:00:00');
        $this->service = new AbonarService($estacion);

        $result = $this->service->abonarBonsai($this->ultimoAbono);

        $this->assertEquals(false, $result);
    }
}