<?php

declare(strict_types=1);


namespace App\Tests\Services\Bonsai;

use App\Services\PulverizarService;
use App\Utils\Bonsai\Tipo;
use PHPUnit\Framework\TestCase;

class PulverizarServicesTest extends TestCase
{
    private PulverizarService $service;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->service = new PulverizarService();
    }

    public function testPulverizarOlmo()
    {
        $tipo = Tipo::OLMO;

        $result = $this->service->pulverizarOlmo($tipo);

        $this->assertIsString($result);
        $this->assertEquals('muy frecuente', $result);
    }

    public function testPulverizarNoOlmo()
    {
        $tipo = Tipo::MANZANO;

        $result = $this->service->pulverizarOlmo($tipo);

        $this->assertNull($result);
    }
}