<?php

declare(strict_types=1);


namespace App\Tests\Services\Bonsai;

use App\Services\TransplantarService;
use PHPUnit\Framework\TestCase;

class TransplantarServicesTest extends TestCase
{
    private TransplantarService $service;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->service = new TransplantarService();
    }

    public function testTransplantarBonsaiRetornaBoleano()
    {
        $result = $this->service->transplantarBonsai();

        self::assertIsBool($result);
    }

    /** @Test*/
    public function testTransplantarBonsaiMarzo()
    {
        $this->service = new TransplantarService(3);

        $result = $this->service->transplantarBonsai();

        $this->assertEquals(true, $result);
    }

    /** @Test*/
    public function testTransplantarBonsaiNoMarzo()
    {
        $this->service = new TransplantarService(4);

        $result = $this->service->transplantarBonsai();

        $this->assertEquals(false, $result);
    }
}