<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container49ZuTs4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container49ZuTs4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container49ZuTs4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container49ZuTs4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container49ZuTs4\App_KernelDevDebugContainer([
    'container.build_hash' => '49ZuTs4',
    'container.build_id' => '60b4c85b',
    'container.build_time' => 1622993285,
], __DIR__.\DIRECTORY_SEPARATOR.'Container49ZuTs4');
