<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8eJSj91\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8eJSj91/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8eJSj91.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8eJSj91\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8eJSj91\App_KernelDevDebugContainer([
    'container.build_hash' => '8eJSj91',
    'container.build_id' => '694d75cc',
    'container.build_time' => 1622818793,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8eJSj91');
